name: controle_tasks
description: Um controlador de tarefas.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-231.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.18.1
  sqflite: ^2.0.0+4
  sqflite_common_ffi: any
  fluttertoast: ^8.0.7
  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
